/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// MultiPodGroupSpecApplyConfiguration represents a declarative configuration of the MultiPodGroupSpec type for use
// with apply.
//
// MultiPodGroupSpec defines the desired state of a MultiPodGroup.
type MultiPodGroupSpecApplyConfiguration struct {
	// ParentRef references an optional MultiPodGroup that this MultiPodGroup belongs to.
	ParentRef *ParentReferenceApplyConfiguration `json:"parentRef,omitempty"`
	// SchedulingPolicy defines the scheduling policy for this instance of the MultiPodGroup.
	// This field is immutable.
	SchedulingPolicy *MultiPodGroupSchedulingPolicyApplyConfiguration `json:"schedulingPolicy,omitempty"`
}

// MultiPodGroupSpecApplyConfiguration constructs a declarative configuration of the MultiPodGroupSpec type for use with
// apply.
func MultiPodGroupSpec() *MultiPodGroupSpecApplyConfiguration {
	return &MultiPodGroupSpecApplyConfiguration{}
}

// WithParentRef sets the ParentRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParentRef field is set to the value of the last call.
func (b *MultiPodGroupSpecApplyConfiguration) WithParentRef(value *ParentReferenceApplyConfiguration) *MultiPodGroupSpecApplyConfiguration {
	b.ParentRef = value
	return b
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *MultiPodGroupSpecApplyConfiguration) WithSchedulingPolicy(value *MultiPodGroupSchedulingPolicyApplyConfiguration) *MultiPodGroupSpecApplyConfiguration {
	b.SchedulingPolicy = value
	return b
}
