/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MultiPodGroupLister helps list MultiPodGroups.
// All objects returned here must be treated as read-only.
type MultiPodGroupLister interface {
	// List lists all MultiPodGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.MultiPodGroup, err error)
	// MultiPodGroups returns an object that can list and get MultiPodGroups.
	MultiPodGroups(namespace string) MultiPodGroupNamespaceLister
	MultiPodGroupListerExpansion
}

// multiPodGroupLister implements the MultiPodGroupLister interface.
type multiPodGroupLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.MultiPodGroup]
}

// NewMultiPodGroupLister returns a new MultiPodGroupLister.
func NewMultiPodGroupLister(indexer cache.Indexer) MultiPodGroupLister {
	return &multiPodGroupLister{listers.New[*schedulingv1alpha2.MultiPodGroup](indexer, schedulingv1alpha2.Resource("multipodgroup"))}
}

// MultiPodGroups returns an object that can list and get MultiPodGroups.
func (s *multiPodGroupLister) MultiPodGroups(namespace string) MultiPodGroupNamespaceLister {
	return multiPodGroupNamespaceLister{listers.NewNamespaced[*schedulingv1alpha2.MultiPodGroup](s.ResourceIndexer, namespace)}
}

// MultiPodGroupNamespaceLister helps list and get MultiPodGroups.
// All objects returned here must be treated as read-only.
type MultiPodGroupNamespaceLister interface {
	// List lists all MultiPodGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.MultiPodGroup, err error)
	// Get retrieves the MultiPodGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1alpha2.MultiPodGroup, error)
	MultiPodGroupNamespaceListerExpansion
}

// multiPodGroupNamespaceLister implements the MultiPodGroupNamespaceLister
// interface.
type multiPodGroupNamespaceLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.MultiPodGroup]
}
