/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsschedulingv1alpha2 "k8s.io/client-go/applyconfigurations/scheduling/v1alpha2"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// MultiPodGroupsGetter has a method to return a MultiPodGroupInterface.
// A group's client should implement this interface.
type MultiPodGroupsGetter interface {
	MultiPodGroups(namespace string) MultiPodGroupInterface
}

// MultiPodGroupInterface has methods to work with MultiPodGroup resources.
type MultiPodGroupInterface interface {
	Create(ctx context.Context, multiPodGroup *schedulingv1alpha2.MultiPodGroup, opts v1.CreateOptions) (*schedulingv1alpha2.MultiPodGroup, error)
	Update(ctx context.Context, multiPodGroup *schedulingv1alpha2.MultiPodGroup, opts v1.UpdateOptions) (*schedulingv1alpha2.MultiPodGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, multiPodGroup *schedulingv1alpha2.MultiPodGroup, opts v1.UpdateOptions) (*schedulingv1alpha2.MultiPodGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv1alpha2.MultiPodGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv1alpha2.MultiPodGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv1alpha2.MultiPodGroup, err error)
	Apply(ctx context.Context, multiPodGroup *applyconfigurationsschedulingv1alpha2.MultiPodGroupApplyConfiguration, opts v1.ApplyOptions) (result *schedulingv1alpha2.MultiPodGroup, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, multiPodGroup *applyconfigurationsschedulingv1alpha2.MultiPodGroupApplyConfiguration, opts v1.ApplyOptions) (result *schedulingv1alpha2.MultiPodGroup, err error)
	MultiPodGroupExpansion
}

// multiPodGroups implements MultiPodGroupInterface
type multiPodGroups struct {
	*gentype.ClientWithListAndApply[*schedulingv1alpha2.MultiPodGroup, *schedulingv1alpha2.MultiPodGroupList, *applyconfigurationsschedulingv1alpha2.MultiPodGroupApplyConfiguration]
}

// newMultiPodGroups returns a MultiPodGroups
func newMultiPodGroups(c *SchedulingV1alpha2Client, namespace string) *multiPodGroups {
	return &multiPodGroups{
		gentype.NewClientWithListAndApply[*schedulingv1alpha2.MultiPodGroup, *schedulingv1alpha2.MultiPodGroupList, *applyconfigurationsschedulingv1alpha2.MultiPodGroupApplyConfiguration](
			"multipodgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schedulingv1alpha2.MultiPodGroup { return &schedulingv1alpha2.MultiPodGroup{} },
			func() *schedulingv1alpha2.MultiPodGroupList { return &schedulingv1alpha2.MultiPodGroupList{} },
			gentype.PrefersProtobuf[*schedulingv1alpha2.MultiPodGroup](),
		),
	}
}
